version: "3"
services:
  genak:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src:ro
    env_file:
      - .env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: example
volumes:
  postgres-db:


